export const SET_QUERY = 'SET_QUERY';
export const REQUEST_FRIENDS = 'REQUEST_FRIENDS';
export const RECEIVE_FRIENDS_SUCCESS = 'RECEIVE_FRIENDS_SUCCESS';
export const RECEIVE_FRIENDS_FAILURE = 'RECEIVE_FRIENDS_FAILURE';
